# Generated by Django 6.0 on 2026-01-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_note1_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.URLField(),
        ),
    ]
